name: Generate Readme
on:
  push:
    branches:
      - ci/generate-readme
jobs:
  generate-readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: "pip install notebook"
    - run: "pip install naas_drivers"
    - run: "pip install papermill"
    - run: "jupyter nbconvert --execute generate_readme.ipynb --inplace"
    - run: "jupyter nbconvert --clear-output --inplace generate_readme.ipynb"
    - run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git checkout main
          git status
          git commit -am "feat: generate templates button and json"
          git push