name: Update documentation
on:
  push:
    branches:
      - master

jobs:
  check-notebooks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: '${{ secrets.PERSONAL_ACCESS_TOKEN }}'
    - run: "make interactive='' update-documentation"
      env:
        PERSONAL_ACCESS_TOKEN: '${{ secrets.PERSONAL_ACCESS_TOKEN }}'